#!/usr/bin/env ruby
$LOAD_PATH.push File.dirname(__FILE__)
$LOAD_PATH.push File.dirname(__FILE__) + '/classes/'

require 'jp_config_loader'
require 'jp_server'

s = JpServer.new Jp::load_config
s.serve
