#!/usr/bin/env ruby

$LOAD_PATH.push File.dirname(__FILE__)
$LOAD_PATH.push File.dirname(__FILE__) + '/classes/'

require 'ruby-1.9.0-compat'
require 'jp_config_loader'
require 'mongo'

# Load options & defaults
options = Jp::load_server_config

options[:mongo_uri] ||= 'mongodb://localhost'
raise ArgumentError.new "mongo_db option must be specified" unless options[:mongo_db]
raise ArgumentError.new "pools option must be specified" unless options[:pools]
raise ArgumentError.new "pools option must not be empty" unless ! options[:pools].empty?

# Connect to mongodb
connection = Mongo::Connection.from_uri options[:mongo_uri]
database = connection.db options[:mongo_db]
options[:pools].each do |name, data|
	next if ARGV[0] && ARGV[0] != name
	pool = database[name]

	total     = pool.count
	available = pool.find(locked: false).count
	acquired  = total - available

	unless ARGV[0]
		print ("#" * (12 + name.size)) + "\n"
		print "##### %s #####\n" % name
		print ("#" * (12 + name.size)) + "\n"
	end

	print "Total:     %d\n" % total
	print "Acquired:  %d\n" % acquired
	print "Available: %d\n" % available
end
