#!/usr/bin/env ruby
$LOAD_PATH.push File.dirname(__FILE__)
$LOAD_PATH.push File.dirname(__FILE__) + '/classes/'
$LOAD_PATH.push File.dirname(__FILE__) + '/lib/rb/'

require 'jp/server/unlocker'
require 'jp/server/configuration_loader'

options = Jp::Server::ConfigurationLoader.server_config

s = Jp::Server::Unlocker.new(options)
s.run
