#!/usr/bin/env ruby
$LOAD_PATH.push File.dirname(__FILE__)
$LOAD_PATH.push File.dirname(__FILE__) + '/classes/'
$LOAD_PATH.push File.dirname(__FILE__) + '/lib/rb/'

require 'jp_config_loader'
require 'jp/server/unlocker'

s = Jp::Server::Unlocker.new Jp::load_server_config
s.run
